---
- name: Setup clock and timezone
  hosts: all
  become: yes
  tasks:
    - name: Ensure correct timezone is set
      timezone:
        name: "Asia/Taipei"

    - name: Install NTP package
      ansible.builtin.package:
        name: ntp
        state: present

    - name: Update and upgrade apt packages
      become: true
      apt:
        update_cache: yes
        upgrade: yes

- name: Install MUNGE on all nodes
  hosts: all
  become: yes

  tasks:
    - name: Update APT package list
      apt:
        update_cache: yes

    - name: Install MUNGE and development package
      apt:
        name:
          - munge
        state: present

- name: Configure MUNGE on head node
  hosts: head-node
  become: yes
  tasks:
    - name: Generate a new munge key
      command: dd if=/dev/urandom of=/etc/munge/munge.key bs=1 count=1024
      args:
        creates: /etc/munge/munge.key
      register: dd_output
      ignore_errors: yes

    - name: Ensure correct permissions for munge key
      file:
        path: /etc/munge/munge.key
        owner: munge
        group: munge
        mode: '0600'
      when: dd_output.changed

    - name: Ensure MUNGE key permissions are correct
      ansible.builtin.file:
        path: "/etc/munge/munge.key"
        owner: munge
        group: munge
        mode: '0600'
        
    - name: Enable and start MUNGE service
      ansible.builtin.systemd:
        name: munge
        enabled: yes
        state: started

- name: Fetch file from head node
  hosts: head-node
  become: yes
  tasks:
    - fetch:
        src: /etc/munge/munge.key
        dest: /tmp/fetched
        flat: yes

- name: Copy file to compute nodes
  hosts: compute-node
  become: yes
  tasks:
    - copy:
        src: /tmp/fetched
        dest: /etc/munge/munge.key
        owner: munge
        group: munge
        mode: '0600'

- name: Restart MUNGE on all nodes
  hosts: all
  become: yes
  tasks:
    - ansible.builtin.systemd:
        name: "munge"
        enabled: yes
        state: restarted