- name: Setup time
  hosts: all
  become: yes
  tasks:
    - name: Ensure correct timezone is set
      timezone:
        name: "Asia/Taipei"

    - name: Install NTP package
      ansible.builtin.package:
        name: ntp
        state: present

    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day